name: osinara-tls

services:
  caddy:
    image: caddy:2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
    environment:
      OSINARA_HOSTNAME: ${OSINARA_HOSTNAME:?OSINARA_HOSTNAME is required}
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - edge-frontend
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /config:size=16m,mode=0700
    volumes:
      - /opt/osinara/tls/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data

networks:
  edge-frontend:
    external: true
    name: osinara-production-edge-frontend

volumes:
  caddy-data:
    name: osinara-tls-caddy-data
